import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'test',
  description: 'Generated by create next app',
        //   <link
        //   rel='apple-touch-icon'
        //   sizes='57x57'
        //   href={('/static/apple-icon-57x57.png')}
        // />

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
